### ISSUE TITLE
API for booking a movie

### ISSUE THREAD

**Issue by mashafrancis** [mashafrancis/cinema-book-out#5]
**Description**
CRUD Endpoint for booking a movie and persisting the data.

**Tasks**

- [ ] Add movie booking details and persist the data

- [ ] Read booked movie details

- [ ] Update booked movie details

- [ ] Delete booking
